### ISSUE TITLE
Data parameter for generate_data.py

### ISSUE THREAD

**Issue by chaizeg** [microsoft/anomalydetector#14]
Hi,
generate_data.py is not taking the path of csv file as one of the parameters. My dataset is in srcnn/data. I get the following error :
![issue](https://user-images.githubusercontent.com/42580324/79564510-177e3280-80af-11ea-89eb-1a88581644a2.PNG)
How do I solve this issue?

**Comment by ngocdangrby** [comment]
Put your dataset (.csv) in a folder in srcnn/data

> eg: srcnn/data/test/dataset1.csv
> srcnn/data/test/dataset2.csv
> ...

then run this command:
`python generate_data.py --data data`

it's worked for me.
