### ISSUE TITLE
Unresolved reference 'median_filter'

### ISSUE THREAD

**Issue by Royalwal** [microsoft/anomalydetector#19]
boundary_utils.py

[import bisect
import numpy as np
from msanomalydetector._anomaly_kernel_cython import median_filter](url)

Unresolved reference 'median_filter'，How to solve this problem

**Comment by guinao** [comment]
please use the following command to compile the cpython module.
`
python setup.py build_ext --inplace
`

**Comment by Royalwal** [comment]
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build

**Comment by guinao** [comment]
Have you installed cython yet? It should be issue that the cython library is not installed. You can use the following command to check if you have all the dependencies.
`pip install -r requirements.txt`

**Comment by Royalwal** [comment]
thank u
