### ISSUE TITLE
Question about saliency map

### ISSUE THREAD

**Issue by littlehappi** [microsoft/anomalydetector#4]
Hi,
The idea about saliency map construction using fft is interesting. But i have some questions here. As we know, time series anomaly detection usually simulates the normal data shape, value or distribution to calculate the distance from the abnormal data, which can be viewed as reconstruction error (e.g. PCA and VAE methods). If the time-series data is mapped to frequency domain and sent to a filter (as shown in the code), the seasonality of the reconstruction data (ifft) is just removed. So why the derived saliency map can represent the abnormal score of the corresponding time-series data? And what is the concrete physical meaning behind the saliency map using fft?

**Comment by jianmohuo** [comment]
Hi, 
My intuition to use fft-based saliency map construction is to remove normal pattern in the series. The idea is inspired by a paper called "Image Signature: Highlighting Sparse Salient Regions"(the same author to spetral residual). The paper proved that if a foreground signal f is sufficiently sparse on time domain, and background is sparse on frequency domain(the card of nonzero elements of frequency < N/6) , then there exists a high expectation that f will still be contained after IDCT[sign(DCT[x])] construction. I suppose SR also has similiar property. I compared the method against SR. The experimental results show that it is weaker than SR in anomaly detection tasks.

Best regards,
Hansheng
